spring:
  datasource:
    url: jdbc:mysql://aliyun.germinal.cc:3306/rbac_demo?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT
    username: rbac_demo
    password: WfXc2isTj5a3GSsF
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 180000
      maximum-pool-size: 15
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    check-template: true
    mode: HTML5

debug: true


logging:
  level:
    root: info
    zx:
      learn:
        rbac_demo: debug
    org:
      mybatis: debug




#        org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

mybatis:
  mapper-locations: classpath:zx/learn/board/mapper/*.xml
  #  config-location: classpath:zx/learn/board/mapper/*.xml
  type-aliases-package: zx.learn.board.entity
  configuration:
    map-underscore-to-camel-case: true

#MyBatis 分页插件设置。
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  default-count: countSql
  row-bounds-with-count: true

server:
  port: 80
