spring:
  datasource:
    url: jdbc:mysql://aliyun.germinal.cc:3306/rbac_demo?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: rbac_demo
    password: WfXc2isTj5a3GSsF
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15

logging:
  level:
    zx:
      learn:
        rbac_demo: debug

mybatis:
  mapper-locations: classpath:zx/learn/board/mapper/*.xml
  #  config-location: classpath:zx/learn/board/mapper/*.xml
  type-aliases-package: zx.learn.board.entity
  configuration:
    map-underscore-to-camel-case: true

#MyBatis 分页插件设置。
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  default-count: countSql
  row-bounds-with-count: true
